extern int AutonSelected;
extern int AutonMin;
extern int AutonMax;

void drawGUI();
void intake_thread();
void intake_color_red();
void intake_color_blue();
void selectAuton();
void AwpStake(bool isright);
void AwpMogo();
void RedElimMogo();
void skills();
void test();
void ElimRing(bool isright);
void ElimMogoRed();
void ElimMogoDisrupt();
void BlueElimRing();
void r1095r();
bool detectcolor2(bool isred);
void testturn();
void SigSoloAWP();
void SoloAWP();
void GoalRush();
void GoalRushStraight();
void SetupGoalRush();
void AwpStake(bool isright);
void NegativeElim();
