extern int AutonSelected;
extern int AutonMin;
extern int AutonMax;

void drawGUI();
void selectAuton();
void Far6TopAntiDisruption();
void Far6LowAntiDisruption();
void Far6Low();
void Far6Top();
void Far6Safe();
void Far6SafeBar();
void Far6SafeNoBar();
void FarAWPInside();
void FarAWPOutside();
void NearElim();
void NearBottomElim();
void NearAWP();
void SoloAWP();
void ProgSkills();
void tag();
void TestDriveMotors();
void TestPID();